os: osx

osx_image: xcode8.4 # define OS X image which will be mounted

language: node_js

node_js: '8'

install:
  # Install all dependencies listed in your package.json file
  - yarn

script:
  - echo "Make app"
  - if [["$TRAVIS_BRANCH" == "master"]]; then yarn make; fi

  - echo "Deploy app to GitHub"
  - if [["$TRAVIS_BRANCH" == "master"]]; then yarn publish; fi
