os: osx

osx_image: xcode8.4 # define OS X image which will be mounted

language: node_js

node_js: '8'

install:
  # Install all dependencies listed in your package.json file
  - yarn

stages:
  - name: make
    if: branch = master
  - name: publish
    if: branch = master

jobs:
  include:
    - stage: make
      script: yarn make
    - stage: publish
      script: yarn publish
