os:
  - osx
  - windows

language: node_js

node_js: '8'

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
install:
  # Install mono and wine
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install mono;
    brew install wine;
    fi

  # Install all dependencies listed in your package.json file
  - npm install

cache:
  directories: node_modules

stages:
  - name: make
    if: branch = master
  # - name: publish
  #   if: branch = master

jobs:
  include:
    - stage: make
      script: npm run make
    # - stage: publish
    #   script: npm run publish
